feat: telas atualizadas
Renan1fps/Project-inter-3 pull request #9
Opened 2022-11-05 21:59 UTC by PedroVitorhj

Atualizei o layoult de umas telas ai

2022-11-05 22:10 UTC, Renan1fps requested changes

2022-11-05 22:10 UTC, Renan1fps commented on gui/menuPrin.fxml
> +                                          <Image url="@../../../../Downloads/Icone-usuario-Png-1024x1024.png" />
voce tem que colocar na pastar imagens  dentro do projeto essa foto, senão quebra pq em outro pc não vai ter

2022-11-05 22:10 UTC, Renan1fps commented on gui_cadastros/cadCar.fxml
> +                  <Image url="@../../../../Downloads/download%20(1).jpg" />
essa imagem também

2022-11-06 02:03 UTC, PedroVitorhj commented on gui/menuPrin.fxml
> +                                          <Image url="@../../../../Downloads/Icone-usuario-Png-1024x1024.png" />
ok

2022-11-06 02:03 UTC, PedroVitorhj commented on gui_cadastros/cadCar.fxml
> +                  <Image url="@../../../../Downloads/download%20(1).jpg" />
coloquei as duas e vou dar commit dnv

2022-11-06 15:36 UTC, Renan1fps approved these changes

2022-11-06 15:36 UTC, merged